# fly.toml app configuration file generated for qwikly-stack on 2023-07-30T22:19:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "qwikly-stack"
primary_region = "cdg"

[[mounts]]
  source = "qwikly_stack_volume"
  destination = "/qwikly_stack_volume"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
